# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWeb3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWeb3
  #pod 'web3swift','0.4.1'
  #pod 'web3swift', git: 'https://github.com/BANKEX/web3swift.git',:commit =>'782d5ee'
  pod 'web3swift','0.5.6'
  #pod 'web3swift', git: 'https://github.com/BANKEX/web3swift.git'

end
